### ISSUE TITLE
dcterms XSD

### ISSUE THREAD

**Issue by HughP** [dcmi/usage#115]
Greetings, 

I'm wondering if the defining XSD file for dcterms is the linked one: https://www.dublincore.org/schemas/xmls/qdc/2006/01/06/dcterms.xsd

If it is not, is there one which is? if it is, then why aren't the following found in it:
* https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/NLM
* https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/RFC5646
* https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/RFC4646
* https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/ISO639-3

**Comment by kcoyle** [comment]
I suspect that the date on that file (2006) is the reason. The question is: should dcterms.xsd be updated? There are properties that have been added since then. 

I also note that the use of syntax encoding schemes, which is based on the DC Abstract Model, has not had much discussion lately. Since most of them are defined outside of DC I wonder if they should be included here as properties or if they should only be referred to in comments. I also wonder if the DC-specific ones, like box, might not have been superseded by better-known standards.

**Comment by HughP** [comment]
Box has not been superseded in the Open Language Archives Community
application profile. OLAC was one of the foundational profiles for OAI.

**Comment by tombaker** [comment]
@HughP There are several issues here:

1. The latest XML schemas are linked to an [XML schema page](https://www.dublincore.org/schemas/xmls/). As far as I can tell, the latest schemas are from 2008.
2. DCMI has not actively maintained the XML schemas since that time. The larger point is that we are not aware of a formal, well-documented interpretation of DCMI metadata terms for use in XML. The XML schemas from 2008 do arguably reflect an implicit model for such an interpretation, but this was never formally described or standardized.
3. The data model for DCMI Metadata Terms today is "based on RDF", even as described in ISO 15836 (see https://github.com/dcmi/usage/issues/119).
4. It is not clear to us that there is an ongoing demand for, or interest in, an updated XML schema, beyond what is currently provided. Updating the schema would implicitly validate the data model underlying the 2008 schema, and we know little about where this model is being followed or even how the 2008 schemas are being used.

In order for DCMI to take this up again, there would need to be a clear demand from DCMI stakeholders, and the endeavor would require a significant effort by a working group to document the requirements and data model.

**Comment by HughP** [comment]
@tombaker did you get my email to you personal account 15 dec 2022? firstname@firstnamelastname.org
 I was trying to contact you outside the context of Github.

I am a bit concerned with this phrasing. Exactly how would the usage board come into the awareness that this need exists? It seems that closing this issue without directing how to further the conversation, effectively shuts down any potential for this conversation.  It seems that raising the question here in the DCMI usage board's discussions doesn't count as raising awareness.

> It is not clear to us that there is an ongoing demand for, or interest in, an updated XML schema, beyond what is currently provided. Updating the schema would implicitly validate the data model underlying the 2008 schema, and we know little about where this model is being followed or even how the 2008 schemas are being used.

Is it not ture that the same can be said about the RDF based implementations of DC Terms. The usage board does not make any statistical  statement about the breadth of use of RDF implementations of DCMI metadata schemes? So how does the usage board know that these technical implementations are being used?

**Comment by kcoyle** [comment]
@HughP We have some information about DC terms usage in RDF through the [Linked Open Vocabularies](https://lov.linkeddata.es/dataset/lov/) project. That show DC Terms as one of the most used vocabularies:

https://lov.linkeddata.es/dataset/lov/vocabs/dcterms

We did once find a statistical account of the dc terms usage in RDF, but I haven't be able to find it since. I did some blog posts about that:
* https://kcoyle.blogspot.com/2013/10/dublin-core-usage-in-lod.html
* https://kcoyle.blogspot.com/2013/10/who-uses-dublin-core-original-15.html

I would love to get more data like this. It would be amazing to get data about other uses - in XML, in JSON - but I don't know how that would be done. All ideas are welcome!
