### ISSUE TITLE
Provide a persistent namespace for the OpenWEMI vocabulary

### ISSUE THREAD

**Issue by niklasl** [dcmi/usage#127]
The DCMI OpenWEMI Community Group has requested that DCMI provide a persistent namespace for the OpenWEMI vocabulary [^1].

The OpenWEMI Community Group considers the vocabulary to be under active development, and further improvements to the vocabulary will depend on feedback from implementators. Without a credibly persistent namespace, however, the group cannot credibly advocate for its implementation.

All namespaces under the DCMI umbrella ultimately fall under the responsibility of the Usage Board, so the request to DCMI for a persistent namespace for the  OpenWEMI vocabulary is ultimately a request to the Usage Board.

## Proposed resolution

The Usage Board recommends that DCMI provide a namespace for the OpenWEMI vocabulary [^2] -- `ns.dublincore.org/openwemi/` -- along with a commitment to keep the  namespace available, to the best of its capacity, as a persistent resource.

Specifically:

1. For the foreseeable future, maintenance responsibility for the OpenWEMI vocabulary would fall to the DCMI OpenWEMI Community Group.

2. Ultimate responsibility for the OpenWEMI namespace would fall to the DCMI Usage Board, though without any implied commitment of the Usage Board to actively maintain the namespace in the long term.

3. The Usage Board is not being asked to approve or endorse the specific contents of the OpenWEMI namespace. Rather, it is merely being asked to agree (or not) that OpenWEMI is important enough, and that its quality is generally good enough, to justify the provision by DCMI of a persistent namespace URI.

4. The OpenWEMI namespace would not fall under the DCMI Namespace Policy[^3], which covers only the "Dublin Core" namespaces. Specifically, while OpenWEMI would be subject to the persistence guarantee provided to all DCMI namespaces, its maintenance would not be bound by the change policies outlined in the namespace policy.

5. The documentation by which the general quality of the OpenWEMI vocabulary should be assessed is found on the OpenWEMI Github repository[^1].

6. In formal terms, approval by the Usage Board is a recommendation submitted to the DCMI Governing Board for official approval.

[^1]: https://github.com/dcmi/openwemi/blob/main/docs/index.md  
[^2]: http://rdf.dev.oclc.org/eor/1997/10/02-dces#  
[^3]: https://www.dublincore.org/specifications/dublin-core/dcmi-namespace/

**Comment by tombaker** [comment]
## Background

Dublin Core was one of the first vocabularies outside of W3C to be published with URIs intended specifically for use in RDF. 

The first provisional URIs for Dublin Core were published with an OCLC namespace in 1997 [^1]. The W3C Recommendation for RDF of February 1999 included a section on "Dublin Core Metadata" (section 7.4), though with the disclaimer that the specific terms shown (with their namespace, `http://purl.org/metadata/dublin_core#`) were subject to replacement with an authoritative reference from the "Dublin Core Initiative" [^2].

A schema posted in March 2000 was the earliest recorded use of the `/elements/1.1/` namespace that is still in use today [^3]. In October 2001, DCMI published a namespace policy covering the `/elements/1.1/`, `/terms/`, `/dcmitype/` namespaces and stating DCMI's commitment to the stability and persistence of its namespaces. This organizational commitment was crucial for the subsequent adoption of Dublin Core [^4].

Since the early 2000s, DCMI has taken on responsibility for namespaces that were developed elsewhere and needed a stable institutional host: the vocabularies of the Learning Resources Metadata Initiative (LRMI), curated since 2014 by the DCMI LRMI Task Group [^5]; the Bibliographic Ontology (BIBO) since 2018 [^6]; and SKOS-Thes since 2023 [^7]. In addition, DCMI has since 2011 maintained a backup of the FOAF vocabulary which, if required by given circumstances, could also be hosted by DCMI [^8].

The original "Dublin Core" namespaces, aka DCMI Metadata Terms, along with their corresponding ISO standards, have since 2001 been actively maintained by the DCMI Usage Board. The other DCMI namespaces also fall ultimately under the responsibiity of the The Usage Board, but the Board has not explicitly committed itself to their active maintenance. The LRMI vocabularies are actively maintained by the DCMI LRMI Task Group, while BIBO and SKOS-Thes are both, at least for now, considered to be frozen.

The OpenWEMI Community Group is now requesting that DCMI provide a persistent namespace for the OpenWEMI vocabulary. This request is in one sense for the same institutional commitment to persistence as provided by the namespace policy, though with some important differences. 

Inasmuch as the Usage Board is group ultimately responsible for the maintenance of all DCMI namespaces -- even those for which maintenance is in practice handled by DCMI working groups (LRMI) or for which active maintenance may not be required, or only rarely (BIBO, SKOS-Thes) -- the creation of a DCMI namespace for the OpenWEMI vocabulary also implies a longer-term commitment by the Board.

---

[^1]: http://rdf.dev.oclc.org/eor/1997/10/02-dces#
[^2]: https://www.w3.org/TR/1999/REC-rdf-syntax-19990222/#examples
[^3]: http://dublincore.org/2000/03/13/dces
[^4]: https://www.dublincore.org/specifications/dublin-core/dcmi-namespace/2001-10-26/
[^5]: https://www.dublincore.org/news/2014/10-24-stewardship-of-lrmi-specification-transferred-to-dcmi/
[^6]: https://www.dublincore.org/news/2018/11-30-bibo/
[^7]: https://www.dublincore.org/news/2023/10-06_dcmi-hosts-skos-thes/
[^8]: https://www.dublincore.org/news/2011/05-02-dcmi-and-the-foaf-project-announce-a-cooperation-agreement/

**Comment by tombaker** [comment]
I have closed #123, which is in effect superseded by this issue. Please refer back to that issue for previous discussion.

**Comment by niklasl** [comment]
VOTE by @niklasl: APPROVE to recommend.

**Comment by bdarcus** [comment]
VOTE by @bdarcus - APPROVE

**Comment by jtennis** [comment]
VOTE by @jtennis - APPROVE

**Comment by kcoyle** [comment]
VOTE by @kcoyle - APPROVE

**Comment by philbarker** [comment]
VOTE by @philbarker - APPROVE

**Comment by annakasprzik** [comment]
VOTE by @annakasprzik - APPROVE

**Comment by tombaker** [comment]
VOTE on behalf of Haliza, who is on break - APPROVE

**Comment by aisaac** [comment]
APPROVE - in fact I just reviewed (and I was late, which explains also this late vote) a paper that would have benefited from the availability of something like OpenWEMI...

**Comment by sehan53** [comment]
APPROVE

**Comment by osma** [comment]
APPROVE

**Comment by niklasl** [comment]
RESOLVED: DCMI Usage Board APPROVES creation of a persistent namespace URI `https://ns.dublincore.org/openwemi/` for OpenWEMI.

Thank you everyone for voting!
