### ISSUE TITLE
Examples for dct:identifier

### ISSUE THREAD

**Issue by tombaker** [dcmi/usage#18]
## PLEASE VOTE ON [COMMENT BELOW](../usage/issues/18#issuecomment-396848947)

See [note_identifier.md](../blob/master/proposals/2018_iso-related/note_identifier.md)

Add examples for [http://purl.org/dc/terms/identifier](http://dublincore.org/documents/2012/06/14/dcmi-terms/#terms-identifier):

    Best practice is to identify the resource by means of a string conforming
    to a formal identification system. Examples of formal identification
    systems include the Uniform Resource Name (URN), the Digital Object
    Identifier (DOI) and the International Standard Book Number (ISBN).

Note: 
* dct:identifier has a range of Literal.
* This would appear in ISO 15836-2 as "NOTE 1 to entry:".

The existing comment reads:
    
    Recommended best practice is to identify the resource by means of a string
    confirming to a formal identification system.

**Comment by tombaker** [comment]
## PLEASE VOTE THUMBS-UP/DOWN

See [note_identifier.md](../blob/master/proposals/2018_iso-related/note_identifier.md)

The existing comment for [http://purl.org/dc/terms/identifier](http://dublincore.org/documents/2012/06/14/dcmi-terms/#terms-identifier) reads:

    Recommended best practice is to identify the resource by means of a string
    confirming to a formal identification system.

Add examples as follows:

    Recommended practice is to identify the resource by means of a string
    conforming to a formal identification system. Examples of formal
    identification systems include the Uniform Resource Name (URN), the Digital
    Object Identifier (DOI), and the International Standard Book Number (ISBN).

Note: 
* dct:identifier has a range of Literal.
* "Recommended practice..." is consistent with approved comments for accrual properties - see #34

**Comment by kcoyle** [comment]
I think the examples bring up more questions than they answer. DOIs are often URIs; I believe that the ISBN is a URN(?); and URNs and DOIs and ISBNs are not at the level of abstraction. I think this is another case for a primer or guidance document, where there can be more of an explanation and examples can be given.

**Comment by makxdekkers** [comment]
And in practice, people use `dct:identifier` with HTTP URIs. As far as I am aware, no-one seems to care about the word _formal_ in the definition.

**Comment by kaiec** [comment]
I use dct:identifier (and explain it that way in my lectures) to list "legacy" identifiers that are strings. ISBNs are not a URN if they are just listed as ISBN10 or ISBN13. You can write a ISBN as URN in this form: urn:ISBN:3-8273-7019-1 but this is not what I find usually in the data. 

As URNs are per definition URIs I would definitely exclude them from the examples. For DOIs it is the same as with ISBNs, they can come as URIs or as plain numbers, usually prefixed by doi:. Contrary to ISBNs, however, it is relatively straight-forward to interpret a DOI as URI with prefix doi = http://doi.org

If we keep the literal range, I suggest something along the following lines:

- Whenever a URI reference is used (e.g. a URN or the http form of a DOI), owl:sameAs should be used.
- For legacy identifiers represented as literals, it is recommended to use a formal identification system, like the International Standard Book Number (ISBN).

**Comment by juhahakala** [comment]
People use dct:identifier both for legacy identifiers such as ISBN, and persistent identifiers such as URN and DOI, which are actionable in the Internet. The latter are at present always expressed as HTTP URIs. Examples ISO WG supplied were intended to show that it is OK to use dct:identifier for both traditional and persistent identifiers. It is OK for me to restore the original note and give just examples of how dct:identifier is used with traditional and persistent identifiers. 

In Finland urn:isbn's are common and you can find them in HTTP URI format in both DC and MARC records. The same applies for Handles, DOIs, etc. 

I have never thought of using dct:identifier for e.g. and ISBN and owl:sameAs for urn:isbn which contains the same ISBN in the namespace specific string. In such case, ISBN and URN identify the same thing, so such usage of OWL is of course possible. But it is also easy to just repeat dct:identifier if both the legacy and actionable identifier are provided. And if only the latter is given, dct:identifier has to be used since owl:sameAs cannot exist alone. And having persistent identifiers in two different places may make processing of DC records more complicated.      

ISO DOI standard published in 2012 recommends the format doi:<doi-string>. This has been replaced by https://doi.org/<doi-string> in Crossref and other DOI communities, so DOIs are often expressed just as HTTP URIs, not in the old doi: format. 

DOI community is planning to register a URN namespace. If and when this happens, there will be URNs in the form urn:doi:<doi-string>. Handle service has already been modified so that HTTP URIs https://doi.org/urn:doi:<doi-string> are actionable, so every DOI can be expressed as URN. But this is not official yet. There are various benefits if this is done; for instance, DOI without the resolver address may not be recognizable in plain text (since there are also other strings than DOIs which begin with 10. and contain "/"). Moreover, if and when the URN community establishes the Global resolver discovery service, any URN including urn:doi:<doi-string> will becom resolvable even without the hardcoded resolver address. And such identifiers will be almost completely technology independent, which is one of the original requirements IETF specified for URNs (and decided to put aside when URI syntax was approved).

**Comment by juhahakala** [comment]
Based on this discussion, I have changed the note in the ISO draft and added two examples: 

Note 1 to entry: Recommended practice is to identify the resource by means of a string conforming to an actionable identification system. 

EXAMPLES	https://doi.org/10.17863/CAM.11283
			http://urn.fi/URN:NBN:fi-fd2017-00011868

**Comment by tombaker** [comment]
@juhahakala @aisaac Is it confusing to say that the identifier is an "actionable" string then, by the choice of examples imply that, by definition, this means an HTTP URI ("actionable" on the Web)?  I tend to agree with Antoine, that this is a good place to put identifiers that are not necessarily used in Linked Data (or in Web data) and that we should keep recommendations minimal in the core spec and leave more specific recommendations to application profiles.  I believe Antoine was proposing the text above, minus "formal":

    Recommended practice is to identify the resource by means of a string
    conforming to a identification system. Examples of formal
    identification systems include the Uniform Resource Name (URN), the Digital
    Object Identifier (DOI), and the International Standard Book Number (ISBN).

**Comment by aisaac** [comment]
Last week @tombaker indicated the issue "needs a bit more discussion" but I believe that we're set, with 4 thumbs-up votes in favour of his proposal, and @kcoyle 's +1 , unless there's an objection in the coming days!

**Comment by stuartasutton** [comment]
I agree with @aisaac and his agreement with @kcoyle.

**Comment by tombaker** [comment]
APPROVED:
```
Recommended practice is to identify the resource by means of a string
conforming to an identification system. Examples of 
identification systems include the Uniform Resource Name (URN), the Digital
Object Identifier (DOI), and the International Standard Book Number (ISBN).
```
