### ISSUE TITLE
definition_Standard.txt

### ISSUE THREAD

**Issue by kcoyle** [dcmi/usage#4]
The current dct definition is so broad as to encompass any resource that one wants to point to for just about any purpose. It has been interpreted by the [W3C DXWG](https://www.w3.org/2017/dxwg/wiki/Main_Page) as the way to link from datasets to (application) profiles and between profiles. This would be true for all profiles, even those that are ad hoc agreements between parties, or solely local or internal practices. It could also be used to link to usage documentation and other related documents. To me this definition is too broad.

That said, the ISO definition is clearly an attempt to define ISO standards as dct:Standard, in particular "established by consensus and approved by a recognized body". Presumably there are standards bodies that rely on voting rather than consensus. It seems to lack any mention of maintenance or a maintenance body which to me is a key element that defines a standard. I would add something to the effect of a standard being a "supported agreement" and something about a "established body with maintenance capability" or some such.

**Comment by kcoyle** [comment]
This is from Makx regarding DCAT:
******
DCAT-AP uses `dct:conformsTo` with range `dct:Standard` in three places:

- For `dcat:CatalogRecord` where it "_refers to an Application Profile that the Dataset’s metadata conforms to_";
- For `dcat:Dataset` where it "_refers to an implementing rule or other specification_";
- For `dcat:Distribution` where it "_refers to an established schema to which the described Distribution conforms_".

In neither of those cases it is expected (although not excluded) that the object is a "standard" in ISO terms. 
*****
It looks to me that these easily fit the DC definition but not the ISO one.

**Comment by jneubert** [comment]
[definition_Standard.md](../blob/master/proposals/definition_Standard.md)

**Comment by tombaker** [comment]
As of June 3, the status of the proposal from ISO WG is in flux (being discussed).  When we finally do have a proposal on the table, I will make sure that the issue we open links back to this one (or replicates its content).  Closing the issue for now.

**Comment by juhahakala** [comment]
The original definition of Standard has been restored and the example has been removed from the ISO draft. 

If and when UB continues discussion about dct:standard, you might decide whether standard is seen as a document or as something that the Oxford English Dictionary describes as "something used as a measure, norm, or model in comparative evaluations"? IMO the former (document) can definitely be catalogued, the latter (norm) perhaps cannot. 

The ISO description was taken from ISO/IEC Guide and specified a standard document, which I believe is a relevant point of view for dct:Standard. If UB wants to retain the spirit of the original definition, I suggest that the current "home made" definition is replaced with an official one from e.g. the OED. And I do hope that it would still be possible to add a second definition (the ISO/IEC one) in which the point of view is that of a standard document. 

The ISO/IEC definition of standard does not cover just ISO or IEC standards, but all standards approved by recognized bodies. Karen said 

"ISO definition is clearly an attempt to define ISO standards as dct:Standard, in particular "established by consensus and approved by a recognized body".  Presumably there are standards bodies that rely on voting rather than consensus."

I beg to differ, since ISO standard process actually does not match the ISO/IEC definition. ISO standards are approved via a well defined voting process which no longer requires consensus. There was a time when consensus was required back in 90's (note that the ISO/IEC definition was written in 1996), but ISO changed the rules many years ago. Therefore for instance IETF's consensus-driven standardization process where no voting is ever done is closer to the ISO/IEC definition than ISO's current process. The ISO definition suits DC as well, since DCMI is a recognized body.
