### ISSUE TITLE
Definition and comment of dct:mediator

### ISSUE THREAD

**Issue by tombaker** [dcmi/usage#44]
After much discussion in Issue #19, including a [clarification from Stuart](https://github.com/dcmi/usage/issues/19#issuecomment-397279986) about the meaning originally intended and a proposal from Stuart (supported by Antoine) that the property perhaps be deprecated, Juha [proposed a further change of definition](https://github.com/dcmi/usage/issues/19#issuecomment-403769845), from:

    entity that mediates access to the resource and for whom the resource is intended or useful

to

    entity that mediates access to the resource

with the comment:

    Note 1 to entry: A mediator might be e.g. a parent, teacher, teaching
    assistant, care-giver, or an organization that has specified document
    accession rights to a resource.

He and a colleague feel that the current text covers both mediator and beneficiary (entity for whom the resource is intended or useful).  He acknowledges that this does change the semantics, but argues that a "mediator" simply cannot be the entity for whom the resource is intended.

As in Issue #19, the usage comment introduces the notion of "document accession rights", not mentioned in DCMI Metadata Terms.

Juha argues that deprecating Mediator is not an option because successive versions of DC terms must be compatible (though Tom points out that Mediator has not yet been part of any ISO standards).

With the change, Juha argues, the Usage Board might consider coining a new property, `beneficiary` because mediator would be an orphan without it.

**Comment by kcoyle** [comment]
Hmmm. What Stuart describes I would probably put in dct:audience, which is the entity for whom the resource is intended. I can see why "mediator" is confusing. What I don't understand, because I wasn't involved, is why so many education terms were added to what is, in my mind, intended to be a general-purpose vocabulary.

Note that I'm trying to run down the current LOV stats. Didn't we do this in another thread?

**Comment by stuartasutton** [comment]
Karen, there was a brief period of time starting in late 1998-99 up through about 2005(?) when the intention was to expand the terms set to include domain specific properties stemming from the DCMI communities. The DC-Education community moved on it and a set of terms from the education effort were approved--audience, conformsTo, educationLevel, instructionalMethod and mediator. The Usage Board served as gateway for what got in and what didn't. Tom's probably best to explain why the effort was phased out...lots of politics, as you might assume. DCMI now has the /dcx/ namespace for more specialized community vocabularies (e.g., /dcx/lrmi-terms/). If tackled again today, the education properties would likely be in a /dcx/education/.

**Comment by kcoyle** [comment]
Thanks, Stuart. I like the idea of /dcx/ - it would be very interesting to know if these could be moved over to there. That would require us to survey users. I know it would be work, but it might be a great improvement in overall usability of dcterms.

**Comment by stuartasutton** [comment]
Karen, currently, both LRMI and terms stemming from the Collections Application Profile are deemed community specifications (see [Community Specifications](http://dublincore.org/documents/#communityspecifications)). Any effort to cleanse /dc/terms/ of everything but terms appropriate to a general purpose vocabulary should also consider whether properties like [dcterms:accrualPeriodicity](http://dublincore.org/documents/dcmi-terms/#terms-accrualPolicy) are any more general than mediator. Also, some terms from the education effort are more generally used (e.g., [dcterms:audience](http://dublincore.org/documents/dcmi-terms/#terms-audience) and [dcterms:conformsTo](http://dublincore.org/documents/dcmi-terms/#terms-conformsTo)). It all may not be so easy to slice and dice.

**Comment by tombaker** [comment]
PROPOSED: Leave as is.

**Comment by osma** [comment]
I'm torn on this. I agree with @juhahakala that the current definition is confusing, even a bit contradictory. Ideally this property would specify only the mediator (e.g. teacher) and some other property - audience comes to mind - would identify the beneficiary (e.g. student). But since this is apparently not used very much, changing it doesn't seem very urgent.

**Comment by jentschk** [comment]
Although I currently see no alternative to "leave as is" and we clarified in yesterday's telcon that deprecating is not an option as long as there is no alternative, I want to note that I see deprecation as the eventually best solution. It seems that the current confusing/contradictory state can not be resolved without either "not making it much better" or imposing a change that wouldn't comply to the policy. The fact that the property isn't much used shouldn't be an argument for it to remain forever. There should eventually be a pin on it saying "we know its a bit odd and we don't like it anymore" so that not every person turning to dct to map data needs to think about it.

**Comment by tombaker** [comment]
## APPROVED
```
An entity that mediates access to the resource.
```

Leave comment unchanged.
