### ISSUE TITLE
Hubble Space Telescope as a "data service"?

### ISSUE THREAD

**Issue by tombaker** [dcmi/usage#61]
We have some feedback from the ISO WG about [the decision to characterize the Hubble telescope as a data service](https://github.com/dcmi/usage/issues/49#issuecomment-430313969): "The telescope is a research tool that produces data, but it is not a data service in the same sense [as] UK Data Service... Therefore to call Hubble telescope a data service may be seen as controversial."

The same commenter accepts that Hubble could be a contributor but questions whether it could also be a creator.  Also, the commenter proposes using its official name: "Hubble Space Telescope".

**Comment by osma** [comment]
Could we just use another epithet, like "scientific instrument"?

**Comment by tombaker** [comment]
Juha writes: "Astronomers seem to think of the telescope as an observatory or just as
an instrument, not primarily as a data producer. I would rather leave
the data producer role to data archives which collect, organize,
preserve and disseminate data. For instance, the data from the Hubble
telescope and its successors will be stored in and disseminated from
MAST, Barbara A. Mikulski Archive for Space Telescopes
(https://archive.stsci.edu/hst/)."

**Comment by aisaac** [comment]
Maybe we can be less precise, like "Hubble telescope (a source of data)"?

**Comment by kcoyle** [comment]
My reading is that it isn't the wording in parentheses that is the problem, but the inclusion of Hubble as a creator. I think the easiest thing is to drop Hubble from the dct:creator examples. This is one of those philosophical questions that will never get full agreement. (The library world is still torn on whether fictive characters can be described as "persons", while millions of people are emotionally closer to the characters in their favorite soap opera than they are to their own family members.)

**Comment by tombaker** [comment]
We have:
* `(data service)` - which I think we agree to reject
* `(scientific instrument)`
* `(a source of data)`

On the other hand, does it really need to be characterized at all?

**Comment by kcoyle** [comment]
Tom, all of the others are characterized, so either none are or all are. And as I said above, I don't think it's the characterization that is a problem but that it is listed as a creator. I agree that we can drop it from creator and from contributor. I myself feel that a scientific instrument can be a source of data but is not an agent as such.

**Comment by osma** [comment]
Can someone remind me where the Hubble example came from? What's the point it is trying to illustrate? 

Could we change it to something else that serves the same purpose but is less problematic and perhaps could be used both as a creator and a contributor?

**Comment by jtennis** [comment]
I still do not follow how an observation instrument does not create data.

**Comment by kcoyle** [comment]
@jtennis You think it can, and I think it can, but clearly some people have problems with it and we don't have the room to explain. For that reason I would just drop it, but once again this points to the need for a guide to usage that can be more verbose.

**Comment by juhahakala** [comment]
I support calling HST "scientific instrument". It is good to indicate that this category of Contributors is OK from DC point of view. Handbook can be more thorough in this respect, and list other non-human (and human) contributor categories. But for the time being I would prefer not to use HST as an example for Creator, since some DC users may see that as controversial. 

I have no fixed opinions on this issue - there are and will be AI programs that use raw data to produce novel scientific results, and in such case the program can be seen as the creator of this information. But a tool or program which does not have a creative component is IMO a different case. MS Word is not my co-author although it does occasionally correct my spelling and stores the text for me. HST captures data, but it needs humans to everything else.

But one of these days AI programs will reach singularity, and a few milliseconds after that they will decide who is and who is not a creator ;-).

**Comment by kcoyle** [comment]
@juhahakala I can go with that, and we'll see if it is accepted. "Scientific instrument" is clear to me.

And I, too, will humbly serve our AI overlords. (In case they are listening.)

**Comment by tombaker** [comment]
DECISION

As an example for Contributor (but not Creator):

    Hubble Space Telescope (scientific instrument)
