### ISSUE TITLE
Examples for dct:format

### ISSUE THREAD

**Issue by tombaker** [dcmi/usage#72]
One reviewer points out that the examples for `dct:format` are only literals, although Format does not have a literal range:

> EXAMPLE 1    text/xml.
> EXAMPLE 2    40 pixels x 512 pixels.
> EXAMPLE 3     22 in.

The reviewer suggests using, as example, `wd:Q489490` aka `https://www.wikidata.org/wiki/Q48940`, the Wikidata property for:

> RDF/XML: syntax defined by the W3C to express an RDF graph as an XML document

**Comment by tombaker** [comment]
STRAWMAN PROPOSAL

As an example for for dct:format, add:

> EXAMPLE 4 https://www.wikidata.org/wiki/Q48940

**Comment by kcoyle** [comment]
Why not use the URL for text/html? (The Wikidata Q names are not yet well known and not easily readable for this purpose.) 

http://www.w3.org/1999/02/22-rdf-syntax-ns#HTML (from the RDF 1.1 Concepts document)

The comment recommends to use a controlled vocabulary, so I think that a majority of the examples should be from controlled vocabularies, which is not the case today. I'd have only one that is a physical size, and I'd go with centimeters, not inches (which is too US centric). Common on library records (in the US) is "23 cm" so that could substitute for one of the size ones.

So I'd go from:

> EXAMPLE 1    text/xml.
> EXAMPLE 2    40 pixels x 512 pixels.
> EXAMPLE 3     22 in.

to 

> EXAMPLE 1    text/xml.
> EXAMPLE 2    http://www.w3.org/1999/02/22-rdf-syntax-ns#HTML
> EXAMPLE 3     23 cm

**Comment by aisaac** [comment]
I am not sure about the HTML example from RDF. That URI is for a literal datatype, which could be slightly different from a format. I.e. something that is in http://www.w3.org/1999/02/22-rdf-syntax-ns#HTML is not quite the same as something in text/html. But anyway it could be ok.

That said, and echoing @kcoyle 's point about using an established controlled vocabulary, how about having a statement that would use a more traditional format, and picked from LCSH or AAT? For example http://vocab.getty.edu/aat/300265438

**Comment by aisaac** [comment]
Call 19-06-2019: we suggest to use a human-friendly URI: http://id.loc.gov/vocabulary/mvidformat/dvd

**Comment by tombaker** [comment]
## PROPOSAL 

    EXAMPLE 1 text/xml.
    EXAMPLE 2 http://id.loc.gov/vocabulary/mvidformat/dvd
    EXAMPLE 3 23 cm

**Comment by tombaker** [comment]
DECISION (see above)
