### ISSUE TITLE
Examples for dct:identifier

### ISSUE THREAD

**Issue by tombaker** [dcmi/usage#73]
The examples for `dct:identifier` are currently:

> EXAMPLE 1 http://doi.org/10.17863/CAM.11283
EXAMPLE 2 http://urn.fi/URN:NBN:fi-fd2017-00011868

One reviewer points out that the range of `dct:identifier` is `rdfs:Literal` and wonders why both examples are URIs.

**Comment by tombaker** [comment]
The reviewer makes an excellent point.  For discussion.

**Comment by kcoyle** [comment]
I think we could add an ISbn in its recognizable form:

`978-1524763138`

And the URN could be in "URN" form:

`URN:NBN:fi-fd2017-00011868`

which looks like a string.

The fact is that identifiers that don't identify themselves (mere strings) are not very useful. It's quite possible that the definition of this element should become "rdfs:literal or rdfs:anyURI".

**Comment by tombaker** [comment]
@kcoyle Are you in effect suggesting that the range be dropped?  The text of the definition makes no reference to range; it is handled with a separate range statement.  Here is the full entry in its current form:

    3.2.26
    identifier
    unambiguous reference to the resource within a given context

    Label   Identifier
    URI      http://purl.org/dc/terms/identifier
    Range  http://www.w3.org/2000/01/rdf-schema#Literal

    EXAMPLE 1 http://doi.org/10.17863/CAM.11283
    EXAMPLE 2 http://urn.fi/URN:NBN:fi-fd2017-00011868

    Note 1 to entry: The recommended practice is to identify the resource 
    by means of a string conforming to an identification system. Examples 
    of identification systems include the Uniform Resource Name (URN), 
    the Digital Object Identifier (DOI) and the International Standard Book 
    Number (ISBN).

**Comment by staplegun** [comment]
I think the problem is that we tried to only show examples that meet the "recommended practice".

The range has to be `rdfs:Literal` (or unspecified) because in reality not everyone can satisfactorily specify their local identifiers as IRIs - there may well be a documented "identification system" but it is not published or based on the IRI syntax.

I think @kcoyle may be right suggesting an ISBN - it's clearly a string but also conforms to an identification system (that is semi-recognisable).

**Comment by kcoyle** [comment]
Tom, This is a hold-over from the pre-RDF world of creating records that name or point to resources rather than having identified resources as the subjects of ones' graph. In essence this should only be used in cases where the identifier is not a URI and is not usable as the subject or object of a triple. Older record-based data has a lot of non-web identifiers. I think we should model the examples to emphasize that this property is a carrier for those identifiers. To be sure, the reality is that we will find "in the wild" examples where the dct:identifier value is given as a URI, but I don't think this is the proper use of that property in good RDF design. So I'm going to go back on what I said and suggest that all examples be given _without_ "http" - a DOI, an NBN (both in URN format) and a plain ISBN string as I suggested before. Some people will still use this with an http URI, but we shouldn't encourage that.

**Comment by paulwalk** [comment]
This has been something of a surprise to me! In my work with metadata describing Open Access scholarly publications, the very common practice is to use dct:identifier to hold URIs (often DOIs in their 'HTTP URI' form, or else repository record URLs).

In recent months there has been some new resistance to this from the point of view of "not all identifiers should be URIs".

**Comment by osma** [comment]
> This is a hold-over from the pre-RDF world of creating records that name or point to resources rather than having identified resources as the subjects of ones' graph

Even in the post-RDF world a resource may well have multiple identifiers, more than one of which may be a URI. Not all of these can be the subject of statements, so it's quite convenient to select one as the main resource and use dct:identifier for the others (somewhat like owl:sameAs, or schema:sameAs, but without the heavy-handed semantics of owl:sameAs).

**Comment by juhahakala** [comment]
We might provide three different examples:
- plain vanilla ISBN (with hyphens, to maximize human readability)
- URN:NBN or URN:ISBN without the resolver address 
- DOI in the Crossref format (ie https://doi.org/<doi>

URN is recognizable and in principle resolvable even without the resolver address, but DOI has to be expressed as HTTP URI. Recommended encoding of identifier strings has to accommodate all these options. 

I have already added ISBN example in the latest draft of the ISO standard.

**Comment by tombaker** [comment]
## PROPOSED - for vote

As examples for `identifier` (3.2.26):

    EXAMPLE 1 http://doi.org/10.17863/CAM.11283
    EXAMPLE 2 URN:NBN:fi-fd2017-00011868
    EXAMPLE 3 978-1524763138

**Comment by aisaac** [comment]
I agree with updating the examples. But can't resist to ask that from the perspective of URIs vs literals, URN:NBN:fi-fd2017-00011868 is in the same side as http://doi.org/10.17863/CAM.11283. It's a fully legit URI, so would rather fit in statements with owl:sameAs and others. It only "looks like a string" as @kcoyle says ;-)

**Comment by osma** [comment]
> EXAMPLE 1 http://doi.org/10.17863/CAM.11283

I believe you mean `https://doi.org/...`

**Comment by tombaker** [comment]
DECISION (see above).
