### ISSUE TITLE
Clarifications of `dateCopyrighted` and proposal for `datePublicDomain`

### ISSUE THREAD

**Issue by tombaker** [dcmi/usage#80]
Juha proposes the following:

"""
dateCopyrighted is "date of copyright of the resource". There are no notes or
examples in the standard clarifying the usage of this element.

The problem is that copyright related legislation and practices vary from one
country to another, so the metadata provided in different countries will be
inconsistent unless more guidance is provided. I suppose this element, in its
present form, is based on the U.S. legislation in which the copyright date used
to have an important role up to 1978. I found the following recommendation from
the Web:

    "Date of copyright is usually the first year of the publication. If the
    work is updated, both the first year of the publication and the year when
    the revised edition was published can be provided. If a range of years is
    given, copyright protection covers all updates during the period."

Alas, if the resource is a work, providing date of copyright in DC metadata as
described above is not relevant even in the U.S. Works are protected by Berne
Convention and national / international legislation. For instance, within EU
copyright for works expires 70 years after the death of the creator. This date
could be provided in DC metadata, but not in dateCopyrighted to avoid
confusion. datePublicDomain could be used instead, with a risk that if the
copyright is extended from 70 years, the dates given will not be correct.

However, if the resource is not a work (author's own intellectual creation) the
rules are different in the EU. In Finland these resources (most photographs,
for instance) will be protected for 50 years from the creation of the resource.
When describing these resources, it is meaningful to provide the year of
creation in dateCopyrighted.  

In order to improve the Dublin Core support for copyright related metadata, I
suggest the following:

* Add a note saying that the recommended use of dateCopyrighted is to provide
  the year the resource was created (not the year is was published or made
  available to the public) when the described resource is not a creative work,
  and it is protected for a range of years from its creation.

* Add a new term, for instance datePublicDomain, in which the copyright
  expiration date (70 years from the death of the creator) may be provided.

If and when we translate Dublin Core to Finnish, we may consider enriching
dateCopyrighted with a note and examples. Otherwise the metadata provided may
be inconsistent, since date of copyright of the resource may mean different
things for people over here. Providing the year of publication for a textual
work is counterproductive and should be avoided.
"""

**Comment by kcoyle** [comment]
Date of Copyright: I honestly don't think we should be trying to define this term in any detail - it is much too complex, and varies in ways that few can address. (See this [chart](https://copyright.cornell.edu/publicdomain), which is only for the US, so imagine if we try to be international). When I've worked on metadata I've advocated for the transcription of actual copyright statements as the only clear evidence. If no statement is available, it's unknown, or you record it in a special field as a guesstimate.

Also, I'm dubious about stating a date for when something entered the public domain. What do we do with Shakespeare? Homer? The Vedas? But even more difficult is the fact that of the post-1923 works in the U.S it is estimated that for about 40%, the work was copyrighted at the time of publication but the current status (e.g. whether it is in the public domain) is unknown. What matters for that is the date of copyright renewal, but honestly we don't want to go there because even that is unknown for a large number of works. If there is a registry in a country that keeps track of public domain works, then you might have some positive information. However, if you find a document online with CC-0 you cannot assume that a date on the document is the date of public domain unless that is stated clearly. 

At best, we can say "Generally the year that copyright is known to have been conferred." And creators of metadata will have to determine what that means for them. As for public domain, I can't think of anything that would work for that, so would not advocate adding such a field to DC.

**Comment by stuartasutton** [comment]
As a recovering intellectual property lawyer, I agree with Karen.

**Comment by aisaac** [comment]
In addition to supporting @kcoyle 's comment I'd like to point out that `datePublicDomain` would be also plagued by jurisdiction aspects. One document can enter in the public domain in one jurisdiction but formally still be restricted in other jurisdictions. While it seems desirable and acceptable (and Europeana does it) to offer the possibility to mark some works as public domain in a rather loose way, asking for a date seems to call for more precision and that would be difficult to do while still ignoring the jurisdiction aspect.

**Comment by tombaker** [comment]
Closing this issue from 2020 because we appear to have consensus against the property as proposed. If such a property were needed, this would now need first to be proposed and discussed as an [issue for the SRAP application profile](https://github.com/dcmi/dc-srap/issues).
